'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeC02Schema = Schema({//esquema de la estructura que va a tener el formularios
    date_created: String,
    //datos tren
    noInspeccion: String,
    noTren: String,
    kilometraje: String,
    horaInicio: String,
    horaTerminacion: String,
    
    operario: { type : Schema.ObjectId, ref: 'User'},

    disp:{
        dm1L: Boolean,
        dm1R: Boolean,
        dm1E: Boolean,
        dm2L: Boolean,
        dm2R: Boolean,
        dm2E: Boolean,
    },
    mangueras:{
        mm1L: Boolean,
        mm1R: Boolean,
        mm1C: Boolean,
        mm2L: Boolean,
        mm2R: Boolean,
        mm2C: Boolean,
    },
    cubiertaF:{
        cfm1L: Boolean,
        cfm1R: Boolean,
        cfm1C: Boolean,
        cfm2L: Boolean,
        cfm2R: Boolean,
        cfm2C: Boolean,
    },
    barra:{
        bm1L: Boolean,
        bm1R: Boolean,
        bm2L: Boolean,
        bm2R: Boolean,
    },
    seguros:{
        sm1L: Boolean,
        sm1R: Boolean,
        sm1C: Boolean,
        sm2L: Boolean,
        sm2R: Boolean,
        sm2C: Boolean,
    },
    mecanismoA:{
        mam1L: Boolean,
        mam1R: Boolean,
        mam1E: Boolean,
        mam2L: Boolean,
        mam2R: Boolean,
        mam2E: Boolean,
    },
    contactos:{
        cm1L: Boolean,
        cm1R: Boolean,
        cm2L: Boolean,
        cm2R: Boolean,
    },
    boquillaA:{
        bam1L: Boolean,
        bam1R: Boolean,
        bam1C: Boolean,
        bam2L: Boolean,
        bam2R: Boolean,
        bam2C: Boolean,
    },
    dispositivoR:{
        drm1L: Boolean,
        drm1R: Boolean,
        drm1C: Boolean,
        drm1E: Boolean,
        drm2L: Boolean,
        drm2R: Boolean,
        drm2C: Boolean,
        drm2E: Boolean,
    },
    sellos:{
        sm1L: Boolean,
        sm1R: Boolean,
        sm1C: Boolean,
        sm2L: Boolean,
        sm2R: Boolean,
        sm2C: Boolean,
    },
    cabezaA:{
        cam1L: Boolean,
        cam1R: Boolean,
        cam1C: Boolean,
        cam2L: Boolean,
        cam2R: Boolean,
        cam2C: Boolean,
    },
    piston:{
        pm1L: Boolean,
        pm1R: Boolean,
        pm1C: Boolean,
        pm1E: Boolean,
        pm2L: Boolean,
        pm2R: Boolean,
        pm2C: Boolean,
        pm2E: Boolean,
    },
    limpieza:{
        lm1L: Boolean,
        lm1R: Boolean,
        lm1C: Boolean,
        lm1E: Boolean,
        lm2L: Boolean,
        lm2R: Boolean,
        lm2C: Boolean,
        lm2E: Boolean,
    },
    electrovalvula:{
        em1L: Boolean,
        em1R: Boolean,
        em1C: Boolean,
        em1E: Boolean,
        em2L: Boolean,
        em2R: Boolean,
        em2C: Boolean,
        em2E: Boolean,
    },
    electrovalvulaA:{
        eam1L: Boolean,
        eam1R: Boolean,
        eam1C: Boolean,
        eam1E: Boolean,
        eam2L: Boolean,
        eam2R: Boolean,
        eam2C: Boolean,
        eam2E: Boolean,
    },
    revision:{
        rm1L: Boolean,
        rm1R: Boolean,
        rm1C: Boolean,
        rm1E: Boolean,
        rm2L: Boolean,
        rm2R: Boolean,
        rm2C: Boolean,
        rm2E: Boolean,
    },
    alturaM1: String,
    alturaM2: String,
    llenadoM1: String,
    llenadoM2: String,

    observaciones: String,
    
    //material utilizado
    codigo1: String,
    desc1: String,
    cant1: String,
    noVale1: Number,

    codigo2: String,
    desc2: String,
    cant2: String,
    noVale2: Number,
    
    codigo3: String,
    desc3: String,
    cant3: String,
    noVale3: Number,

    codigo4: String,
    desc4: String,
    cant4: String,
    noVale4: Number,

    codigo5: String,
    desc5: String,
    cant5: String,
    noVale5: Number,
    
    codigo6: String,
    desc6: String,
    cant6: String,
    noVale6: Number,
    
    codigo7: String,
    desc7: String,
    cant7: String, 
    noVale7: Number,
    
    codigo8: String,
    desc8: String,
    cant8: String,
    noVale8: Number,
    
    codigo9: String,
    desc9: String,
    cant9: String,
    noVale9: Number,
    
    codigo10: String,
    desc10: String,
    cant10: String,
    noVale10: Number,

    superviso: { type : Schema.ObjectId, ref: 'User'},
    jefeTurno: { type : Schema.ObjectId, ref: 'User'},
    sMM: { type : Schema.ObjectId, ref: 'User'},
    clave: String
});
module.exports = mongoose.model('mmmeC02', mmmeC02Schema);