'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeC22Schema = Schema({//esquema de la estructura que va a tener el formulario
    date_created: String,
    //datos tren
    noInspeccion: String,
    noTren: String,
    kilometraje: String,
    horaInicio: String,
    horaTerminacion: String,
    
    operario1: { type : Schema.ObjectId, ref: 'User'},
    operario2: { type : Schema.ObjectId, ref: 'User'},

    cajaRevm1D1: Boolean,
    cajaRevm1D2: Boolean,
    cajaRevm1D3: Boolean,
    cajaRevm1I1: Boolean,
    cajaRevm1I2: Boolean,
    cajaRevm1I3: Boolean,
    cajaRevm2D1: Boolean,
    cajaRevm2D2: Boolean,
    cajaRevm2D3: Boolean,
    cajaRevm2I1: Boolean,
    cajaRevm2I2: Boolean,
    cajaRevm2I3: Boolean,

    cajaLimpm1D1: Boolean,
    cajaLimpm1D2: Boolean,
    cajaLimpm1D3: Boolean,
    cajaLimpm1I1: Boolean,
    cajaLimpm1I2: Boolean,
    cajaLimpm1I3: Boolean,
    cajaLimpm2D1: Boolean,
    cajaLimpm2D2: Boolean,
    cajaLimpm2D3: Boolean,
    cajaLimpm2I1: Boolean,
    cajaLimpm2I2: Boolean,
    cajaLimpm2I3: Boolean,

    cajaEngm1D1: Boolean,
    cajaEngm1D2: Boolean,
    cajaEngm1D3: Boolean,
    cajaEngm1I1: Boolean,
    cajaEngm1I2: Boolean,
    cajaEngm1I3: Boolean,
    cajaEngm2D1: Boolean,
    cajaEngm2D2: Boolean,
    cajaEngm2D3: Boolean,
    cajaEngm2I1: Boolean,
    cajaEngm2I2: Boolean,
    cajaEngm2I3: Boolean,

    tapaRevm1D1: Boolean,
    tapaRevm1D2: Boolean,
    tapaRevm1D3: Boolean,
    tapaRevm1I1: Boolean,
    tapaRevm1I2: Boolean,
    tapaRevm1I3: Boolean,
    tapaRevm2D1: Boolean,
    tapaRevm2D2: Boolean,
    tapaRevm2D3: Boolean,
    tapaRevm2I1: Boolean,
    tapaRevm2I2: Boolean,
    tapaRevm2I3: Boolean,

    tapaLimpm1D1: Boolean,
    tapaLimpm1D2: Boolean,
    tapaLimpm1D3: Boolean,
    tapaLimpm1I1: Boolean,
    tapaLimpm1I2: Boolean,
    tapaLimpm1I3: Boolean,
    tapaLimpm2D1: Boolean,
    tapaLimpm2D2: Boolean,
    tapaLimpm2D3: Boolean,
    tapaLimpm2I1: Boolean,
    tapaLimpm2I2: Boolean,
    tapaLimpm2I3: Boolean,

    tornilloRevm1D1: Boolean,
    tornilloRevm1D2: Boolean,
    tornilloRevm1D3: Boolean,
    tornilloRevm1I1: Boolean,
    tornilloRevm1I2: Boolean,
    tornilloRevm1I3: Boolean,
    tornilloRevm2D1: Boolean,
    tornilloRevm2D2: Boolean,
    tornilloRevm2D3: Boolean,
    tornilloRevm2I1: Boolean,
    tornilloRevm2I2: Boolean,
    tornilloRevm2I3: Boolean,

    tornilloLimpm1D1: Boolean,
    tornilloLimpm1D2: Boolean,
    tornilloLimpm1D3: Boolean,
    tornilloLimpm1I1: Boolean,
    tornilloLimpm1I2: Boolean,
    tornilloLimpm1I3: Boolean,
    tornilloLimpm2D1: Boolean,
    tornilloLimpm2D2: Boolean,
    tornilloLimpm2D3: Boolean,
    tornilloLimpm2I1: Boolean,
    tornilloLimpm2I2: Boolean,
    tornilloLimpm2I3: Boolean,

    rodamientosRevm1D1: Boolean,
    rodamientosRevm1D2: Boolean,
    rodamientosRevm1D3: Boolean,
    rodamientosRevm1I1: Boolean,
    rodamientosRevm1I2: Boolean,
    rodamientosRevm1I3: Boolean,
    rodamientosRevm2D1: Boolean,
    rodamientosRevm2D2: Boolean,
    rodamientosRevm2D3: Boolean,
    rodamientosRevm2I1: Boolean,
    rodamientosRevm2I2: Boolean,
    rodamientosRevm2I3: Boolean,

    rodamientosLimpm1D1: Boolean,
    rodamientosLimpm1D2: Boolean,
    rodamientosLimpm1D3: Boolean,
    rodamientosLimpm1I1: Boolean,
    rodamientosLimpm1I2: Boolean,
    rodamientosLimpm1I3: Boolean,
    rodamientosLimpm2D1: Boolean,
    rodamientosLimpm2D2: Boolean,
    rodamientosLimpm2D3: Boolean,
    rodamientosLimpm2I1: Boolean,
    rodamientosLimpm2I2: Boolean,
    rodamientosLimpm2I3: Boolean,

    rodamientosEngm1D1: Boolean,
    rodamientosEngm1D2: Boolean,
    rodamientosEngm1D3: Boolean,
    rodamientosEngm1I1: Boolean,
    rodamientosEngm1I2: Boolean,
    rodamientosEngm1I3: Boolean,
    rodamientosEngm2D1: Boolean,
    rodamientosEngm2D2: Boolean,
    rodamientosEngm2D3: Boolean,
    rodamientosEngm2I1: Boolean,
    rodamientosEngm2I2: Boolean,
    rodamientosEngm2I3: Boolean,

    observaciones: String,

    //material utilizado
    codigo1: String,
    desc1: String,
    cant1: String,
    noVale1: Number,

    codigo2: String,
    desc2: String,
    cant2: String,
    noVale2: Number,
    
    codigo3: String,
    desc3: String,
    cant3: String,
    noVale3: Number,

    codigo4: String,
    desc4: String,
    cant4: String,
    noVale4: Number,

    codigo5: String,
    desc5: String,
    cant5: String,
    noVale5: Number,
    
    codigo6: String,
    desc6: String,
    cant6: String,
    noVale6: Number,
    
    codigo7: String,
    desc7: String,
    cant7: String, 
    noVale7: Number,
    
    codigo8: String,
    desc8: String,
    cant8: String,
    noVale8: Number,
    
    codigo9: String,
    desc9: String,
    cant9: String,
    noVale9: Number,
    
    codigo10: String,
    desc10: String,
    cant10: String,
    noVale10: Number,

    superviso: { type : Schema.ObjectId, ref: 'User'},
    jefeTurno: { type : Schema.ObjectId, ref: 'User'},
    sMM: { type : Schema.ObjectId, ref: 'User'},
    clave: String
});
module.exports = mongoose.model('mmmeC22', mmmeC22Schema);