'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmeC01Schema = Schema({//esquema de la estructura que va a tener el formularios
    date_created: String,
    //datos tren
    noInspeccion: String,
    noTren: String,
    kilometraje: String,
    horaInicio: String,
    horaTerminacion: String,
    
    operario: { type : Schema.ObjectId, ref: 'User'},

    piston1:{
        p1m1L1: Boolean,
        p1m1A1: Boolean,
        p1m1L2: Boolean,
        p1m1A2: Boolean,
        p1m1L3: Boolean,
        p1m1A3: Boolean,
        p1m1L4: Boolean,
        p1m1A4: Boolean,
        p1m1L5: Boolean,
        p1m1A5: Boolean,
        p1m1L6: Boolean,
        p1m1A6: Boolean,
        p1m2L1: Boolean,
        p1m2A1: Boolean,
        p1m2L2: Boolean,
        p1m2A2: Boolean,
        p1m2L3: Boolean,
        p1m2A3: Boolean,
        p1m2L4: Boolean,
        p1m2A4: Boolean,
        p1m2L5: Boolean,
        p1m2A5: Boolean,
        p1m2L6: Boolean,
        p1m2A6: Boolean,
    },
    esprea1:{
        e1m1L1: Boolean,
        e1m1A1: Boolean,
        e1m1L2: Boolean,
        e1m1A2: Boolean,
        e1m1L3: Boolean,
        e1m1A3: Boolean,
        e1m1L4: Boolean,
        e1m1A4: Boolean,
        e1m1L5: Boolean,
        e1m1A5: Boolean,
        e1m1L6: Boolean,
        e1m1A6: Boolean,
        e1m2L1: Boolean,
        e1m2A1: Boolean,
        e1m2L2: Boolean,
        e1m2A2: Boolean,
        e1m2L3: Boolean,
        e1m2A3: Boolean,
        e1m2L4: Boolean,
        e1m2A4: Boolean,
        e1m2L5: Boolean,
        e1m2A5: Boolean,
        e1m2L6: Boolean,
        e1m2A6: Boolean,
    },
    piston2:{
        p2m1L1: Boolean,
        p2m1A1: Boolean,
        p2m1L2: Boolean,
        p2m1A2: Boolean,
        p2m1L3: Boolean,
        p2m1A3: Boolean,
        p2m1L4: Boolean,
        p2m1A4: Boolean,
        p2m1L5: Boolean,
        p2m1A5: Boolean,
        p2m1L6: Boolean,
        p2m1A6: Boolean,
        p2m2L1: Boolean,
        p2m2A1: Boolean,
        p2m2L2: Boolean,
        p2m2A2: Boolean,
        p2m2L3: Boolean,
        p2m2A3: Boolean,
        p2m2L4: Boolean,
        p2m2A4: Boolean,
        p2m2L5: Boolean,
        p2m2A5: Boolean,
        p2m2L6: Boolean,
        p2m2A6: Boolean,
    },
    esprea2:{
        e2m1L1: Boolean,
        e2m1A1: Boolean,
        e2m1L2: Boolean,
        e2m1A2: Boolean,
        e2m1L3: Boolean,
        e2m1A3: Boolean,
        e2m1L4: Boolean,
        e2m1A4: Boolean,
        e2m1L5: Boolean,
        e2m1A5: Boolean,
        e2m1L6: Boolean,
        e2m1A6: Boolean,
        e2m2L1: Boolean,
        e2m2A1: Boolean,
        e2m2L2: Boolean,
        e2m2A2: Boolean,
        e2m2L3: Boolean,
        e2m2A3: Boolean,
        e2m2L4: Boolean,
        e2m2A4: Boolean,
        e2m2L5: Boolean,
        e2m2A5: Boolean,
        e2m2L6: Boolean,
        e2m2A6: Boolean,
    },
    valvula1:{
        v1m1L1: Boolean,
        v1m1A1: Boolean,
        v1m1L2: Boolean,
        v1m1A2: Boolean,
        v1m1L3: Boolean,
        v1m1A3: Boolean,
        v1m1L4: Boolean,
        v1m1A4: Boolean,
        v1m1L5: Boolean,
        v1m1A5: Boolean,
        v1m1L6: Boolean,
        v1m1A6: Boolean,
        v1m2L1: Boolean,
        v1m2A1: Boolean,
        v1m2L2: Boolean,
        v1m2A2: Boolean,
        v1m2L3: Boolean,
        v1m2A3: Boolean,
        v1m2L4: Boolean,
        v1m2A4: Boolean,
        v1m2L5: Boolean,
        v1m2A5: Boolean,
        v1m2L6: Boolean,
        v1m2A6: Boolean,
    },
    valvula2:{
        v2m1L1: Boolean,
        v2m1A1: Boolean,
        v2m1L2: Boolean,
        v2m1A2: Boolean,
        v2m1L3: Boolean,
        v2m1A3: Boolean,
        v2m1L4: Boolean,
        v2m1A4: Boolean,
        v2m1L5: Boolean,
        v2m1A5: Boolean,
        v2m1L6: Boolean,
        v2m1A6: Boolean,
        v2m2L1: Boolean,
        v2m2A1: Boolean,
        v2m2L2: Boolean,
        v2m2A2: Boolean,
        v2m2L3: Boolean,
        v2m2A3: Boolean,
        v2m2L4: Boolean,
        v2m2A4: Boolean,
        v2m2L5: Boolean,
        v2m2A5: Boolean,
        v2m2L6: Boolean,
        v2m2A6: Boolean,
    },
    nivelAceiteM1: String,
    nivelAceiteM2: String,

    mangueraE:{
        mem1R1: Boolean,
        mem1A1: Boolean,
        mem1R2: Boolean,
        mem1A2: Boolean,
        mem1R3: Boolean,
        mem1A3: Boolean,
        mem1R4: Boolean,
        mem1A4: Boolean,
        mem1R5: Boolean,
        mem1A5: Boolean,
        mem1R6: Boolean,
        mem1A6: Boolean,
        mem2R1: Boolean,
        mem2A1: Boolean,
        mem2R2: Boolean,
        mem2A2: Boolean,
        mem2R3: Boolean,
        mem2A3: Boolean,
        mem2R4: Boolean,
        mem2A4: Boolean,
        mem2R5: Boolean,
        mem2A5: Boolean, 
        mem2R2: Boolean,
        mem2A2: Boolean,
    },
    mangueraS:{
        msm1R1: Boolean,
        msm1A1: Boolean,
        msm1R2: Boolean,
        msm1A2: Boolean,
        msm1R3: Boolean,
        msm1A3: Boolean,
        msm1R4: Boolean,
        msm1A4: Boolean,
        msm1R5: Boolean,
        msm1A5: Boolean,
        msm1R6: Boolean,
        msm1A6: Boolean,
        msm2R1: Boolean,
        msm2A1: Boolean,
        msm2R2: Boolean,
        msm2A2: Boolean,
        msm2R3: Boolean,
        msm2A3: Boolean,
        msm2R4: Boolean,
        msm2A4: Boolean,
        msm2R5: Boolean,
        msm2A5: Boolean, 
        msm2R2: Boolean,
        msm2A2: Boolean,
    },
    tornilloA:{
        tam1R1: Boolean,
        tam1A1: Boolean,
        tam1R2: Boolean,
        tam1A2: Boolean,
        tam1R3: Boolean,
        tam1A3: Boolean,
        tam1R4: Boolean,
        tam1A4: Boolean,
        tam1R5: Boolean,
        tam1A5: Boolean,
        tam1R6: Boolean,
        tam1A6: Boolean,
        tam2R1: Boolean,
        tam2A1: Boolean,
        tam2R2: Boolean,
        tam2A2: Boolean,
        tam2R3: Boolean,
        tam2A3: Boolean,
        tam2R4: Boolean,
        tam2A4: Boolean,
        tam2R5: Boolean,
        tam2A5: Boolean, 
        tam2R2: Boolean,
        tam2A2: Boolean,
    },
    tornilloE:{
        tem1R1: Boolean,
        tem1A1: Boolean,
        tem1R2: Boolean,
        tem1A2: Boolean,
        tem1R3: Boolean,
        tem1A3: Boolean,
        tem1R4: Boolean,
        tem1A4: Boolean,
        tem1R5: Boolean,
        tem1A5: Boolean,
        tem1R6: Boolean,
        tem1A6: Boolean,
        tem2R1: Boolean,
        tem2A1: Boolean,
        tem2R2: Boolean,
        tem2A2: Boolean,
        tem2R3: Boolean,
        tem2A3: Boolean,
        tem2R4: Boolean,
        tem2A4: Boolean,
        tem2R5: Boolean,
        tem2A5: Boolean, 
        tem2R2: Boolean,
        tem2A2: Boolean,
    },

    observaciones: String,
    
    //material utilizado
    codigo1: String,
    desc1: String,
    cant1: String,
    noVale1: Number,

    codigo2: String,
    desc2: String,
    cant2: String,
    noVale2: Number,
    
    codigo3: String,
    desc3: String,
    cant3: String,
    noVale3: Number,

    codigo4: String,
    desc4: String,
    cant4: String,
    noVale4: Number,

    codigo5: String,
    desc5: String,
    cant5: String,
    noVale5: Number,
    
    codigo6: String,
    desc6: String,
    cant6: String,
    noVale6: Number,
    
    codigo7: String,
    desc7: String,
    cant7: String, 
    noVale7: Number,
    
    codigo8: String,
    desc8: String,
    cant8: String,
    noVale8: Number,
    
    codigo9: String,
    desc9: String,
    cant9: String,
    noVale9: Number,
    
    codigo10: String,
    desc10: String,
    cant10: String,
    noVale10: Number,
    
    codigo11: String,
    desc11: String,
    cant11: String,
    noVale11: Number,

    codigo12: String,
    desc12: String,
    cant12: String,
    noVale12: Number,
    
    codigo13: String,
    desc13: String,
    cant13: String,
    noVale13: Number,
    
    codigo14: String,
    desc14: String,
    cant14: String,
    noVale14: Number,
    
    codigo15: String,
    desc15: String,
    cant15: String,
    noVale15: Number,

    superviso: { type : Schema.ObjectId, ref: 'User'},
    jefeTurno: { type : Schema.ObjectId, ref: 'User'},
    sMM: { type : Schema.ObjectId, ref: 'User'},
    clave: String
});
module.exports = mongoose.model('mmmeC01', mmmeC01Schema);