'use strict'//usar novedades de JS

var mongoose = require('mongoose');//modulo de moongose
var Schema = mongoose.Schema;//Schema carga moongoose.Schema esto permite definir nuevos esquemas

var mmmaM14_2Schema = Schema({//esquema de la estructura que va a tener el formulario

    date_created: String,
    //datos tren
    noInspeccion: String,
    noTren: String,
    kilometraje: String,
    fechaInicio: String,
    fechaTerminacion: String,
    
    //1. UBICACION DE VENTANAS M1 Y/O M2 LADO IZQUIERDO Y/O DERECHO
    operario1: { type : Schema.ObjectId, ref: 'User'},
    operario2: { type : Schema.ObjectId, ref: 'User'},
    operario3: { type : Schema.ObjectId, ref: 'User'},
    operario4: { type : Schema.ObjectId, ref: 'User'},

    //DESMONTAJE
    marcarPosicionVentanaM1VLizq1: Boolean,
    marcarPosicionVentanaM1VLizq2: Boolean,
    marcarPosicionVentanaM1VLder1: Boolean,
    marcarPosicionVentanaM1VLder2: Boolean,
    marcarPosicionVentanaM1VCizq1: Boolean,
    marcarPosicionVentanaM1VCizq2: Boolean,
    marcarPosicionVentanaM1VCder1: Boolean,
    marcarPosicionVentanaM1VCder2: Boolean,
    marcarPosicionVentanaM2VLizq1: Boolean,
    marcarPosicionVentanaM2VLizq2: Boolean,
    marcarPosicionVentanaM2VLder1: Boolean,
    marcarPosicionVentanaM2VLder2: Boolean,
    marcarPosicionVentanaM2VCizq1: Boolean,
    marcarPosicionVentanaM2VCizq2: Boolean,
    marcarPosicionVentanaM2VCder1: Boolean,
    marcarPosicionVentanaM2VCder2: Boolean,
    observacionesMpv: String,

    retirarElementosFijacionM1VLizq1: Boolean,
    retirarElementosFijacionM1VLizq2: Boolean,
    retirarElementosFijacionM1VLder1: Boolean,
    retirarElementosFijacionM1VLder2: Boolean,
    retirarElementosFijacionM1VCizq1: Boolean,
    retirarElementosFijacionM1VCizq2: Boolean,
    retirarElementosFijacionM1VCder1: Boolean,
    retirarElementosFijacionM1VCder2: Boolean,
    retirarElementosFijacionM2VLizq1: Boolean,
    retirarElementosFijacionM2VLizq2: Boolean,
    retirarElementosFijacionM2VLder1: Boolean,
    retirarElementosFijacionM2VLder2: Boolean,
    retirarElementosFijacionM2VCizq1: Boolean,
    retirarElementosFijacionM2VCizq2: Boolean,
    retirarElementosFijacionM2VCder1: Boolean,
    retirarElementosFijacionM2VCder2: Boolean,
    observacionesRef: String,

    retirarMarcoInternoM1VLizq1: Boolean,
    retirarMarcoInternoM1VLizq2: Boolean,
    retirarMarcoInternoM1VLder1: Boolean,
    retirarMarcoInternoM1VLder2: Boolean,
    retirarMarcoInternoM1VCizq1: Boolean,
    retirarMarcoInternoM1VCizq2: Boolean,
    retirarMarcoInternoM1VCder1: Boolean,
    retirarMarcoInternoM1VCder2: Boolean,
    retirarMarcoInternoM2VLizq1: Boolean,
    retirarMarcoInternoM2VLizq2: Boolean,
    retirarMarcoInternoM2VLder1: Boolean,
    retirarMarcoInternoM2VLder2: Boolean,
    retirarMarcoInternoM2VCizq1: Boolean,
    retirarMarcoInternoM2VCizq2: Boolean,
    retirarMarcoInternoM2VCder1: Boolean,
    retirarMarcoInternoM2VCder2: Boolean,
    observacionesRmi: String,

    desmontarVentanaM1VLizq1: Boolean,
    desmontarVentanaM1VLizq2: Boolean,
    desmontarVentanaM1VLder1: Boolean,
    desmontarVentanaM1VLder2: Boolean,
    desmontarVentanaM1VCizq1: Boolean,
    desmontarVentanaM1VCizq2: Boolean,
    desmontarVentanaM1VCder1: Boolean,
    desmontarVentanaM1VCder2: Boolean,
    desmontarVentanaM2VLizq1: Boolean,
    desmontarVentanaM2VLizq2: Boolean,
    desmontarVentanaM2VLder1: Boolean,
    desmontarVentanaM2VLder2: Boolean,
    desmontarVentanaM2VCizq1: Boolean,
    desmontarVentanaM2VCizq2: Boolean,
    desmontarVentanaM2VCder1: Boolean,
    desmontarVentanaM2VCder2: Boolean,
    observacionesDv: String,

    ensamblarVentanaM1VLizq1: Boolean,
    ensamblarVentanaM1VLizq2: Boolean,
    ensamblarVentanaM1VLder1: Boolean,
    ensamblarVentanaM1VLder2: Boolean,
    ensamblarVentanaM1VCizq1: Boolean,
    ensamblarVentanaM1VCizq2: Boolean,
    ensamblarVentanaM1VCder1: Boolean,
    ensamblarVentanaM1VCder2: Boolean,
    ensamblarVentanaM2VLizq1: Boolean,
    ensamblarVentanaM2VLizq2: Boolean,
    ensamblarVentanaM2VLder1: Boolean,
    ensamblarVentanaM2VLder2: Boolean,
    ensamblarVentanaM2VCizq1: Boolean,
    ensamblarVentanaM2VCizq2: Boolean,
    ensamblarVentanaM2VCder1: Boolean,
    ensamblarVentanaM2VCder2: Boolean,
    observacionesEv: String,

    //TRABAJOS EN BANCO
    limpiezaGeneralM1VLizq1: Boolean,
    limpiezaGeneralM1VLizq2: Boolean,
    limpiezaGeneralM1VLder1: Boolean,
    limpiezaGeneralM1VLder2: Boolean,
    limpiezaGeneralM1VCizq1: Boolean,
    limpiezaGeneralM1VCizq2: Boolean,
    limpiezaGeneralM1VCder1: Boolean,
    limpiezaGeneralM1VCder2: Boolean,
    limpiezaGeneralM2VLizq1: Boolean,
    limpiezaGeneralM2VLizq2: Boolean,
    limpiezaGeneralM2VLder1: Boolean,
    limpiezaGeneralM2VLder2: Boolean,
    limpiezaGeneralM2VCizq1: Boolean,
    limpiezaGeneralM2VCizq2: Boolean,
    limpiezaGeneralM2VCder1: Boolean,
    limpiezaGeneralM2VCder2: Boolean,
    observacionesLg: String,

    revisionMarcoVM1VLizq1: Boolean,
    revisionMarcoVM1VLizq2: Boolean,
    revisionMarcoVM1VLder1: Boolean,
    revisionMarcoVM1VLder2: Boolean,
    revisionMarcoVM1VCizq1: Boolean,
    revisionMarcoVM1VCizq2: Boolean,
    revisionMarcoVM1VCder1: Boolean,
    revisionMarcoVM1VCder2: Boolean,
    revisionMarcoVM2VLizq1: Boolean,
    revisionMarcoVM2VLizq2: Boolean,
    revisionMarcoVM2VLder1: Boolean,
    revisionMarcoVM2VLder2: Boolean,
    revisionMarcoVM2VCizq1: Boolean,
    revisionMarcoVM2VCizq2: Boolean,
    revisionMarcoVM2VCder1: Boolean,
    revisionMarcoVM2VCder2: Boolean,
    observacionesRmv: String,

    revisionMarcoAM1VLizq1: Boolean,
    revisionMarcoAM1VLizq2: Boolean,
    revisionMarcoAM1VLder1: Boolean,
    revisionMarcoAM1VLder2: Boolean,
    revisionMarcoAM1VCizq1: Boolean,
    revisionMarcoAM1VCizq2: Boolean,
    revisionMarcoAM1VCder1: Boolean,
    revisionMarcoAM1VCder2: Boolean,
    revisionMarcoAM2VLizq1: Boolean,
    revisionMarcoAM2VLizq2: Boolean,
    revisionMarcoAM2VLder1: Boolean,
    revisionMarcoAM2VLder2: Boolean,
    revisionMarcoAM2VCizq1: Boolean,
    revisionMarcoAM2VCizq2: Boolean,
    revisionMarcoAM2VCder1: Boolean,
    revisionMarcoAM2VCder2: Boolean,
    observacionesRma: String,

    revisionElastomerosM1VLizq1: Boolean,
    revisionElastomerosM1VLizq2: Boolean,
    revisionElastomerosM1VLder1: Boolean,
    revisionElastomerosM1VLder2: Boolean,
    revisionElastomerosM1VCizq1: Boolean,
    revisionElastomerosM1VCizq2: Boolean,
    revisionElastomerosM1VCder1: Boolean,
    revisionElastomerosM1VCder2: Boolean,
    revisionElastomerosM2VLizq1: Boolean,
    revisionElastomerosM2VLizq2: Boolean,
    revisionElastomerosM2VLder1: Boolean,
    revisionElastomerosM2VLder2: Boolean,
    revisionElastomerosM2VCizq1: Boolean,
    revisionElastomerosM2VCizq2: Boolean,
    revisionElastomerosM2VCder1: Boolean,
    revisionElastomerosM2VCder2: Boolean,
    observacionesRe: String,

    revisionCristalVM1VLizq1: Boolean,
    revisionCristalVM1VLizq2: Boolean,
    revisionCristalVM1VLder1: Boolean,
    revisionCristalVM1VLder2: Boolean,
    revisionCristalVM1VCizq1: Boolean,
    revisionCristalVM1VCizq2: Boolean,
    revisionCristalVM1VCder1: Boolean,
    revisionCristalVM1VCder2: Boolean,
    revisionCristalVM2VLizq1: Boolean,
    revisionCristalVM2VLizq2: Boolean,
    revisionCristalVM2VLder1: Boolean,
    revisionCristalVM2VLder2: Boolean,
    revisionCristalVM2VCizq1: Boolean,
    revisionCristalVM2VCizq2: Boolean,
    revisionCristalVM2VCder1: Boolean,
    revisionCristalVM2VCder2: Boolean,
    observacionesRcv: String,

    revisarCristalAM1VLizq1: Boolean,
    revisarCristalAM1VLizq2: Boolean,
    revisarCristalAM1VLder1: Boolean,
    revisarCristalAM1VLder2: Boolean,
    revisarCristalAM1VCizq1: Boolean,
    revisarCristalAM1VCizq2: Boolean,
    revisarCristalAM1VCder1: Boolean,
    revisarCristalAM1VCder2: Boolean,
    revisarCristalAM2VLizq1: Boolean,
    revisarCristalAM2VLizq2: Boolean,
    revisarCristalAM2VLder1: Boolean,
    revisarCristalAM2VLder2: Boolean,
    revisarCristalAM2VCizq1: Boolean,
    revisarCristalAM2VCizq2: Boolean,
    revisarCristalAM2VCder1: Boolean,
    revisarCristalAM2VCder2: Boolean,
    observacionesRca: String,

    revisionSeguroAM1VLizq1: Boolean,
    revisionSeguroAM1VLizq2: Boolean,
    revisionSeguroAM1VLder1: Boolean,
    revisionSeguroAM1VLder2: Boolean,
    revisionSeguroAM1VCizq1: Boolean,
    revisionSeguroAM1VCizq2: Boolean,
    revisionSeguroAM1VCder1: Boolean,
    revisionSeguroAM1VCder2: Boolean,
    revisionSeguroAM2VLizq1: Boolean,
    revisionSeguroAM2VLizq2: Boolean,
    revisionSeguroAM2VLder1: Boolean,
    revisionSeguroAM2VLder2: Boolean,
    revisionSeguroAM2VCizq1: Boolean,
    revisionSeguroAM2VCizq2: Boolean,
    revisionSeguroAM2VCder1: Boolean,
    revisionSeguroAM2VCder2: Boolean,
    observacionesRsa: String,

    revisionJaladeraM1VLizq1: Boolean,
    revisionJaladeraM1VLizq2: Boolean,
    revisionJaladeraM1VLder1: Boolean,
    revisionJaladeraM1VLder2: Boolean,
    revisionJaladeraM1VCizq1: Boolean,
    revisionJaladeraM1VCizq2: Boolean,
    revisionJaladeraM1VCder1: Boolean,
    revisionJaladeraM1VCder2: Boolean,
    revisionJaladeraM2VLizq1: Boolean,
    revisionJaladeraM2VLizq2: Boolean,
    revisionJaladeraM2VLder1: Boolean,
    revisionJaladeraM2VLder2: Boolean,
    revisionJaladeraM2VCizq1: Boolean,
    revisionJaladeraM2VCizq2: Boolean,
    revisionJaladeraM2VCder1: Boolean,
    revisionJaladeraM2VCder2: Boolean,
    observacionesRj: String,

    revisionMarcoIM1VLizq1: Boolean,
    revisionMarcoIM1VLizq2: Boolean,
    revisionMarcoIM1VLder1: Boolean,
    revisionMarcoIM1VLder2: Boolean,
    revisionMarcoIM1VCizq1: Boolean,
    revisionMarcoIM1VCizq2: Boolean,
    revisionMarcoIM1VCder1: Boolean,
    revisionMarcoIM1VCder2: Boolean,
    revisionMarcoIM2VLizq1: Boolean,
    revisionMarcoIM2VLizq2: Boolean,
    revisionMarcoIM2VLder1: Boolean,
    revisionMarcoIM2VLder2: Boolean,
    revisionMarcoIM2VCizq1: Boolean,
    revisionMarcoIM2VCizq2: Boolean,
    revisionMarcoIM2VCder1: Boolean,
    revisionMarcoIM2VCder2: Boolean,
    observacionesRm: String,

    extraccionPijasM1VLizq1: Boolean,
    extraccionPijasM1VLizq2: Boolean,
    extraccionPijasM1VLder1: Boolean,
    extraccionPijasM1VLder2: Boolean,
    extraccionPijasM1VCizq1: Boolean,
    extraccionPijasM1VCizq2: Boolean,
    extraccionPijasM1VCder1: Boolean,
    extraccionPijasM1VCder2: Boolean,
    extraccionPijasM2VLizq1: Boolean,
    extraccionPijasM2VLizq2: Boolean,
    extraccionPijasM2VLder1: Boolean,
    extraccionPijasM2VLder2: Boolean,
    extraccionPijasM2VCizq1: Boolean,
    extraccionPijasM2VCizq2: Boolean,
    extraccionPijasM2VCder1: Boolean,
    extraccionPijasM2VCder2: Boolean,
    observacionesEp: String,

    revisionAmortiguadoresM1VLizq1: Boolean,
    revisionAmortiguadoresM1VLizq2: Boolean,
    revisionAmortiguadoresM1VLder1: Boolean,
    revisionAmortiguadoresM1VLder2: Boolean,
    revisionAmortiguadoresM1VCizq1: Boolean,
    revisionAmortiguadoresM1VCizq2: Boolean,
    revisionAmortiguadoresM1VCder1: Boolean,
    revisionAmortiguadoresM1VCder2: Boolean,
    revisionAmortiguadoresM2VLizq1: Boolean,
    revisionAmortiguadoresM2VLizq2: Boolean,
    revisionAmortiguadoresM2VLder1: Boolean,
    revisionAmortiguadoresM2VLder2: Boolean,
    revisionAmortiguadoresM2VCizq1: Boolean,
    revisionAmortiguadoresM2VCizq2: Boolean,
    revisionAmortiguadoresM2VCder1: Boolean,
    revisionAmortiguadoresM2VCder2: Boolean,
    observacionesRa: String,

    cambioCristalVM1VLizq1: Boolean,
    cambioCristalVM1VLizq2: Boolean,
    cambioCristalVM1VLder1: Boolean,
    cambioCristalVM1VLder2: Boolean,
    cambioCristalVM1VCizq1: Boolean,
    cambioCristalVM1VCizq2: Boolean,
    cambioCristalVM1VCder1: Boolean,
    cambioCristalVM1VCder2: Boolean,
    cambioCristalVM2VLizq1: Boolean,
    cambioCristalVM2VLizq2: Boolean,
    cambioCristalVM2VLder1: Boolean,
    cambioCristalVM2VLder2: Boolean,
    cambioCristalVM2VCizq1: Boolean,
    cambioCristalVM2VCizq2: Boolean,
    cambioCristalVM2VCder1: Boolean,
    cambioCristalVM2VCder2: Boolean,
    observacionesCcv: String,

    cambioCristalAM1VLizq1: Boolean,
    cambioCristalAM1VLizq2: Boolean,
    cambioCristalAM1VLder1: Boolean,
    cambioCristalAM1VLder2: Boolean,
    cambioCristalAM1VCizq1: Boolean,
    cambioCristalAM1VCizq2: Boolean,
    cambioCristalAM1VCder1: Boolean,
    cambioCristalAM1VCder2: Boolean,
    cambioCristalAM2VLizq1: Boolean,
    cambioCristalAM2VLizq2: Boolean,
    cambioCristalAM2VLder1: Boolean,
    cambioCristalAM2VLder2: Boolean,
    cambioCristalAM2VCizq1: Boolean,
    cambioCristalAM2VCizq2: Boolean,
    cambioCristalAM2VCder1: Boolean,
    cambioCristalAM2VCder2: Boolean,
    observacionesCca: String,

    aplicarSiliconCM1VLizq1: Boolean,
    aplicarSiliconCM1VLizq2: Boolean,
    aplicarSiliconCM1VLder1: Boolean,
    aplicarSiliconCM1VLder2: Boolean,
    aplicarSiliconCM1VCizq1: Boolean,
    aplicarSiliconCM1VCizq2: Boolean,
    aplicarSiliconCM1VCder1: Boolean,
    aplicarSiliconCM1VCder2: Boolean,
    aplicarSiliconCM2VLizq1: Boolean,
    aplicarSiliconCM2VLizq2: Boolean,
    aplicarSiliconCM2VLder1: Boolean,
    aplicarSiliconCM2VLder2: Boolean,
    aplicarSiliconCM2VCizq1: Boolean,
    aplicarSiliconCM2VCizq2: Boolean,
    aplicarSiliconCM2VCder1: Boolean,
    aplicarSiliconCM2VCder2: Boolean,
    observacionesAsc: String,

    sellarSiliconM1VLizq1: Boolean,
    sellarSiliconM1VLizq2: Boolean,
    sellarSiliconM1VLder1: Boolean,
    sellarSiliconM1VLder2: Boolean,
    sellarSiliconM1VCizq1: Boolean,
    sellarSiliconM1VCizq2: Boolean,
    sellarSiliconM1VCder1: Boolean,
    sellarSiliconM1VCder2: Boolean,
    sellarSiliconM2VLizq1: Boolean,
    sellarSiliconM2VLizq2: Boolean,
    sellarSiliconM2VLder1: Boolean,
    sellarSiliconM2VLder2: Boolean,
    sellarSiliconM2VCizq1: Boolean,
    sellarSiliconM2VCizq2: Boolean,
    sellarSiliconM2VCder1: Boolean,
    sellarSiliconM2VCder2: Boolean,
    observacionesSs: String,

    asentarPinturaNM1VLizq1: Boolean,
    asentarPinturaNM1VLizq2: Boolean,
    asentarPinturaNM1VLder1: Boolean,
    asentarPinturaNM1VLder2: Boolean,
    asentarPinturaNM1VCizq1: Boolean,
    asentarPinturaNM1VCizq2: Boolean,
    asentarPinturaNM1VCder1: Boolean,
    asentarPinturaNM1VCder2: Boolean,
    asentarPinturaNM2VLizq1: Boolean,
    asentarPinturaNM2VLizq2: Boolean,
    asentarPinturaNM2VLder1: Boolean,
    asentarPinturaNM2VLder2: Boolean,
    asentarPinturaNM2VCizq1: Boolean,
    asentarPinturaNM2VCizq2: Boolean,
    asentarPinturaNM2VCder1: Boolean,
    asentarPinturaNM2VCder2: Boolean,
    observacionesApn: String,

    prepararVentanaM1VLizq1: Boolean,
    prepararVentanaM1VLizq2: Boolean,
    prepararVentanaM1VLder1: Boolean,
    prepararVentanaM1VLder2: Boolean,
    prepararVentanaM1VCizq1: Boolean,
    prepararVentanaM1VCizq2: Boolean,
    prepararVentanaM1VCder1: Boolean,
    prepararVentanaM1VCder2: Boolean,
    prepararVentanaM2VLizq1: Boolean,
    prepararVentanaM2VLizq2: Boolean,
    prepararVentanaM2VLder1: Boolean,
    prepararVentanaM2VLder2: Boolean,
    prepararVentanaM2VCizq1: Boolean,
    prepararVentanaM2VCizq2: Boolean,
    prepararVentanaM2VCder1: Boolean,
    prepararVentanaM2VCder2: Boolean,
    observacionesPv: String,

    aplicarPinturaM1VLizq1: Boolean,
    aplicarPinturaM1VLizq2: Boolean,
    aplicarPinturaM1VLder1: Boolean,
    aplicarPinturaM1VLder2: Boolean,
    aplicarPinturaM1VCizq1: Boolean,
    aplicarPinturaM1VCizq2: Boolean,
    aplicarPinturaM1VCder1: Boolean,
    aplicarPinturaM1VCder2: Boolean,
    aplicarPinturaM2VLizq1: Boolean,
    aplicarPinturaM2VLizq2: Boolean,
    aplicarPinturaM2VLder1: Boolean,
    aplicarPinturaM2VLder2: Boolean,
    aplicarPinturaM2VCizq1: Boolean,
    aplicarPinturaM2VCizq2: Boolean,
    aplicarPinturaM2VCder1: Boolean,
    aplicarPinturaM2VCder2: Boolean,
    observacionesAp: String,

    ubicarVentanaM1VLizq1: Boolean,
    ubicarVentanaM1VLizq2: Boolean,
    ubicarVentanaM1VLder1: Boolean,
    ubicarVentanaM1VLder2: Boolean,
    ubicarVentanaM1VCizq1: Boolean,
    ubicarVentanaM1VCizq2: Boolean,
    ubicarVentanaM1VCder1: Boolean,
    ubicarVentanaM1VCder2: Boolean,
    ubicarVentanaM2VLizq1: Boolean,
    ubicarVentanaM2VLizq2: Boolean,
    ubicarVentanaM2VLder1: Boolean,
    ubicarVentanaM2VLder2: Boolean,
    ubicarVentanaM2VCizq1: Boolean,
    ubicarVentanaM2VCizq2: Boolean,
    ubicarVentanaM2VCder1: Boolean,
    ubicarVentanaM2VCder2: Boolean,
    observacionesUv: String,

    separarVentanaM1VLizq1: Boolean,
    separarVentanaM1VLizq2: Boolean,
    separarVentanaM1VLder1: Boolean,
    separarVentanaM1VLder2: Boolean,
    separarVentanaM1VCizq1: Boolean,
    separarVentanaM1VCizq2: Boolean,
    separarVentanaM1VCder1: Boolean,
    separarVentanaM1VCder2: Boolean,
    separarVentanaM2VLizq1: Boolean,
    separarVentanaM2VLizq2: Boolean,
    separarVentanaM2VLder1: Boolean,
    separarVentanaM2VLder2: Boolean,
    separarVentanaM2VCizq1: Boolean,
    separarVentanaM2VCizq2: Boolean,
    separarVentanaM2VCder1: Boolean,
    separarVentanaM2VCder2: Boolean,
    observacionesSv: String,

    aplicarSiliconM1VLizq1: Boolean,
    aplicarSiliconM1VLizq2: Boolean,
    aplicarSiliconM1VLder1: Boolean,
    aplicarSiliconM1VLder2: Boolean,
    aplicarSiliconM1VCizq1: Boolean,
    aplicarSiliconM1VCizq2: Boolean,
    aplicarSiliconM1VCder1: Boolean,
    aplicarSiliconM1VCder2: Boolean,
    aplicarSiliconM2VLizq1: Boolean,
    aplicarSiliconM2VLizq2: Boolean,
    aplicarSiliconM2VLder1: Boolean,
    aplicarSiliconM2VLder2: Boolean,
    aplicarSiliconM2VCizq1: Boolean,
    aplicarSiliconM2VCizq2: Boolean,
    aplicarSiliconM2VCder1: Boolean,
    aplicarSiliconM2VCder2: Boolean,
    observacionesAs: String,

    montarVentanaM1VLizq1: Boolean,
    montarVentanaM1VLizq2: Boolean,
    montarVentanaM1VLder1: Boolean,
    montarVentanaM1VLder2: Boolean,
    montarVentanaM1VCizq1: Boolean,
    montarVentanaM1VCizq2: Boolean,
    montarVentanaM1VCder1: Boolean,
    montarVentanaM1VCder2: Boolean,
    montarVentanaM2VLizq1: Boolean,
    montarVentanaM2VLizq2: Boolean,
    montarVentanaM2VLder1: Boolean,
    montarVentanaM2VLder2: Boolean,
    montarVentanaM2VCizq1: Boolean,
    montarVentanaM2VCizq2: Boolean,
    montarVentanaM2VCder1: Boolean,
    montarVentanaM2VCder2: Boolean,
    observacionesMv: String,

    colocarMarcoIM1VLizq1: Boolean,
    colocarMarcoIM1VLizq2: Boolean,
    colocarMarcoIM1VLder1: Boolean,
    colocarMarcoIM1VLder2: Boolean,
    colocarMarcoIM1VCizq1: Boolean,
    colocarMarcoIM1VCizq2: Boolean,
    colocarMarcoIM1VCder1: Boolean,
    colocarMarcoIM1VCder2: Boolean,
    colocarMarcoIM2VLizq1: Boolean,
    colocarMarcoIM2VLizq2: Boolean,
    colocarMarcoIM2VLder1: Boolean,
    colocarMarcoIM2VLder2: Boolean,
    colocarMarcoIM2VCizq1: Boolean,
    colocarMarcoIM2VCizq2: Boolean,
    colocarMarcoIM2VCder1: Boolean,
    colocarMarcoIM2VCder2: Boolean,
    observacionesCmi: String,

    colocarPijasM1VLizq1: Boolean,
    colocarPijasM1VLizq2: Boolean,
    colocarPijasM1VLder1: Boolean,
    colocarPijasM1VLder2: Boolean,
    colocarPijasM1VCizq1: Boolean,
    colocarPijasM1VCizq2: Boolean,
    colocarPijasM1VCder1: Boolean,
    colocarPijasM1VCder2: Boolean,
    colocarPijasM2VLizq1: Boolean,
    colocarPijasM2VLizq2: Boolean,
    colocarPijasM2VLder1: Boolean,
    colocarPijasM2VLder2: Boolean,
    colocarPijasM2VCizq1: Boolean,
    colocarPijasM2VCizq2: Boolean,
    colocarPijasM2VCder1: Boolean,
    colocarPijasM2VCder2: Boolean,
    observacionesCp: String,

    revisarFuncionamientoM1VLizq1: Boolean,
    revisarFuncionamientoM1VLizq2: Boolean,
    revisarFuncionamientoM1VLder1: Boolean,
    revisarFuncionamientoM1VLder2: Boolean,
    revisarFuncionamientoM1VCizq1: Boolean,
    revisarFuncionamientoM1VCizq2: Boolean,
    revisarFuncionamientoM1VCder1: Boolean,
    revisarFuncionamientoM1VCder2: Boolean,
    revisarFuncionamientoM2VLizq1: Boolean,
    revisarFuncionamientoM2VLizq2: Boolean,
    revisarFuncionamientoM2VLder1: Boolean,
    revisarFuncionamientoM2VLder2: Boolean,
    revisarFuncionamientoM2VCizq1: Boolean,
    revisarFuncionamientoM2VCizq2: Boolean,
    revisarFuncionamientoM2VCder1: Boolean,
    revisarFuncionamientoM2VCder2: Boolean,
    observacionesRf: String,

    pulirCristalM1VLizq1: Boolean,
    pulirCristalM1VLizq2: Boolean,
    pulirCristalM1VLder1: Boolean,
    pulirCristalM1VLder2: Boolean,
    pulirCristalM1VCizq1: Boolean,
    pulirCristalM1VCizq2: Boolean,
    pulirCristalM1VCder1: Boolean,
    pulirCristalM1VCder2: Boolean,
    pulirCristalM2VLizq1: Boolean,
    pulirCristalM2VLizq2: Boolean,
    pulirCristalM2VLder1: Boolean,
    pulirCristalM2VLder2: Boolean,
    pulirCristalM2VCizq1: Boolean,
    pulirCristalM2VCizq2: Boolean,
    pulirCristalM2VCder1: Boolean,
    pulirCristalM2VCder2: Boolean,
    observacionesPc: String,

    retirarExcesoSM1VLizq1: Boolean,
    retirarExcesoSM1VLizq2: Boolean,
    retirarExcesoSM1VLder1: Boolean,
    retirarExcesoSM1VLder2: Boolean,
    retirarExcesoSM1VCizq1: Boolean,
    retirarExcesoSM1VCizq2: Boolean,
    retirarExcesoSM1VCder1: Boolean,
    retirarExcesoSM1VCder2: Boolean,
    retirarExcesoSM2VLizq1: Boolean,
    retirarExcesoSM2VLizq2: Boolean,
    retirarExcesoSM2VLder1: Boolean,
    retirarExcesoSM2VLder2: Boolean,
    retirarExcesoSM2VCizq1: Boolean,
    retirarExcesoSM2VCizq2: Boolean,
    retirarExcesoSM2VCder1: Boolean,
    retirarExcesoSM2VCder2: Boolean,
    observacionesRes: String,

    //MATERIAL UTILIZADO
    codigo1: String,
    desc1: String,
    cant1: String,
    noVale1: Number,
    observaciones1: String,

    codigo2: String,
    desc2: String,
    cant2: String,
    noVale2: Number,
    observaciones2: String,
    
    codigo3: String,
    desc3: String,
    cant3: String,
    noVale3: Number,
    observaciones3: String,

    codigo4: String,
    desc4: String,
    cant4: String,
    noVale4: Number,
    observaciones4: String,

    codigo5: String,
    desc5: String,
    cant5: String,
    noVale5: Number,
    observaciones5: String,
    
    codigo6: String,
    desc6: String,
    cant6: String,
    noVale6: Number,
    observaciones6: String,

    codigo7: String,
    desc7: String,
    cant7: String, 
    noVale7: Number,
    observaciones7: String,

    codigo8: String,
    desc8: String,
    cant8: String,
    noVale8: Number,
    observaciones8: String,

    codigo9: String,
    desc9: String,
    cant9: String,
    noVale9: Number,
    observaciones9: String,

    codigo10: String,
    desc10: String,
    cant10: String,
    noVale10: Number,
    observaciones10: String,

    codigo11: String,
    desc11: String,
    cant11: String,
    noVale11: Number,
    observaciones11: String,

    codigo12: String,
    desc12: String,
    cant12: String,
    noVale12: Number,
    observaciones12: String,

    codigo13: String,
    desc13: String,
    cant13: String,
    noVale13: Number,
    observaciones13: String,

    codigo14: String,
    desc14: String,
    cant14: String,
    noVale14: Number,
    observaciones14: String,

    codigo15: String,
    desc15: String,
    cant15: String,
    noVale15: Number,
    observaciones15: String,

    codigo16: String,
    desc16: String,
    cant16: String,
    noVale16: Number,
    observaciones16: String,

    codigo17: String,
    desc17: String,
    cant17: String,
    noVale17: Number,
    observaciones17: String,

    codigo18: String,
    desc18: String,
    cant18: String,
    noVale18: Number,
    observaciones18: String,

    codigo19: String,
    desc19: String,
    cant19: String,
    noVale19: Number,
    observaciones19: String,

    codigo20: String,
    desc20: String,
    cant20: String,
    noVale20: Number,
    observaciones20: String,

    supervisor: { type : Schema.ObjectId, ref: 'User'},
    jefeMM: { type : Schema.ObjectId, ref: 'User'},
    sMM: { type : Schema.ObjectId, ref: 'User'},
    clave: String
});
module.exports = mongoose.model('mmmaM14_2', mmmaM14_2Schema);